# Generated by Django 3.2.3 on 2021-06-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0003_alter_contactus_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='desctiption',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='profice_pic',
            new_name='profile_pic',
        ),
    ]
