# Generated by Django 3.2.3 on 2021-06-27 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0004_auto_20210622_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trainee.student'),
        ),
    ]
