# Generated by Django 3.2.3 on 2021-07-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0005_alter_contactus_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='qualification',
            field=models.CharField(default='B.tech', max_length=100),
            preserve_default=False,
        ),
    ]
