# Generated by Django 3.2.3 on 2021-06-22 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_auto_20210514_1549'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='profice_pic',
            new_name='profile_pic',
        ),
    ]
