# Generated by Django 3.2.3 on 2021-06-21 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20210609_0937'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='batch',
            options={},
        ),
        migrations.AddField(
            model_name='batch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
