# Generated by Django 3.2.3 on 2021-06-28 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_batch_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='link_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='batch',
            name='meeting_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
